<?php

/**
 * @file
 * Module file.
 */

/**
 * Condition: users' email addresses must end with one of the specified domains.
 *
 * @param object $post
 *   The election post object.
 * @param object $account
 *   The Drupal user account object.
 * @param array $data
 *   An array of allowed domains.
 *
 * @return bool
 *   Whether the email address ends in one of the domains.
 */
function election_example_conditions_check_mail_domain(stdClass $post, stdClass $account, array $data) {
  if ($account->uid == 0 || !$account->mail) {
    return FALSE;
  }
  $at_pos = strpos($account->mail, '@');
  $domain = substr($account->mail, $at_pos);
  return in_array($domain, $data);
}
