name = acdis
description = Standard default layout for ACDIS
preview = preview.png
template = acdis-layout

; Regions
regions[leaderboard_top]= Leaderboard Top
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[masthead]		= Masthead
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[content_bottom] = Content Bottom
regions[footer]         = Footer
